# Generated by Django 4.2.7 on 2023-11-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activation_key',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
